### ISSUE TITLE
这个组件， 可以让寄存器显示值吗？

### ISSUE THREAD

**Issue by putao0525** [sfurkan20/qemu-gdb-debug#1]
![image](https://github.com/sfurkan20/qemu-gdb-debug/assets/12529019/fdab07d3-b280-4dbb-8ac9-5c6cfaf89f22)

1. 能不能在launch 中配置启动？ 
2. 能不能让寄存器的值显示不出来呢？ 
3.

**Comment by saliccio** [comment]
Hayır. Bu eklentinin amacı, QEMU'nun çalışmasının GDB'yi bloklamasını engellemektir. Yazdığınız problemler ile bir alakası yoktur.
